apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: teste-api-node
  annotations:
    github.com/project-slug: joseviniciusnunes/teste-react  
    backstage.io/techdocs-ref: dir:.   
spec:
  type: service
  lifecycle: beta
  owner: team-d
  definition: |
      openapi: "3.0.0"
      info:
        version: 1.0.0
        title: Artist API
        license:
          name: MIT
      servers:
        - url: http://artist.spotify.net/v1
      paths:
        /artists:
          get:
            summary: List all artists
