apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste-react
  annotations:
    github.com/project-slug: joseviniciusnunes/teste-react  
    backstage.io/techdocs-ref: dir:.    
spec:
  type: service
  lifecycle: unknown
  owner: team-d
  implements-apis:
    - doc-api-swagger  
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: doc-api-swagger
spec:
  type: openapi
  url: https://raw.githubusercontent.com/joseviniciusnunes/api-teste-node-express/master/doc.yaml
